### PR TITLE
Add support for string array.

### PR DESCRIPTION
**Pull request by cassiohub**

### CODE REVIEW

**Comment by Schmicko** [comment]
Hey Cássio,

I'm not sure I understand the use case you're trying to solve here. Could you give me an example of how you'd use this.

Cheers,
Mike

**Comment by cassiohub** [comment]
I needed a way to add multiple lines of text on a document, so I built an array of strings and passed it as a parameter of `after` function. The problem now is: it print also the commas between array elements. 

I Had to write a new function that allow an array as parameter and print only the array elements itselfs.

**Comment by Schmicko** [comment]
Hi Cassio,

If I understand what you're getting at, I think you can do that with the existing methods.

Something like this should work.

```javascript
gulp.task('inject:after', function(){
    gulp.src('src/example.html')
        .pipe(inject.after('</title>',
              '\n<!--'
            + '\n This is a multiline comment'
            + '\n injected after the title tag.'
            + '\n -->'
        ))
        .pipe(rename('after.html'))
        .pipe(gulp.dest('build'));
});
```

**Comment by Schmicko** [comment]
Or if you want to use array syntax you could do this.

```javascript
gulp.task('inject:after', function(){
    gulp.src('src/example.html')
        .pipe(inject.after('</title>',
            [
                '<!--',
                ' This is a multiline comment',
                ' injected after the title tag.',
                ' -->'
            ].join('\n');
        ))
        .pipe(rename('after.html'))
        .pipe(gulp.dest('build'));
});
```

**Pull request closed without merging**
